### ISSUE TITLE
optimiser - QWeb2: Template 'OptimiserColorPicker' not found

### ISSUE THREAD

**Issue by Eric0329** [MRLIVING/odoo#15]
```
Traceback:
Error: QWeb2: Template 'OptimiserColorPicker' not found

at Object.exception (http://35.201.207.141:8069/web/content/440-f17a3d4/web.assets_common.js:3692:7)
at Engine._render (http://35.201.207.141:8069/web/content/440-f17a3d4/web.assets_common.js:3737:103)
at Engine.render (http://35.201.207.141:8069/web/content/440-f17a3d4/web.assets_common.js:3733:151)
at Class.renderElement (http://35.201.207.141:8069/web/content/440-f17a3d4/web.assets_common.js:4091:1137)
at http://35.201.207.141:8069/web/content/440-f17a3d4/web.assets_common.js:4101:6
```

**Comment by Eric0329** [comment]
It has been solved after Restart the ODOO server.
```
by OdooGuys on 5/15/20, 10:22 PM
Hi, thank you for contacting us.

Please, first of all, check that you have extracted all the files from the archive, maybe you are missing some files.

After that restart your odoo server and then go to apps and update the Optimiser module.

After that go and check it again.

In addition, your error may be related to the cache, so enable the developer mode with assets, and then disable it. And after that check again.
```
