### ISSUE TITLE
TypeError: not all arguments converted during string formatting

### ISSUE THREAD

**Issue by Eric0329** [MRLIVING/odoo#3]
```
2019-05-22 11:11:14,762 18679 ERROR hoogahome odoo.addons.payment.controllers.portal: Error while processing transaction(s) [143], exception "not all arguments converted during string formatting"                                                                                                     
Traceback (most recent call last):                                                                                                                  
  File "/usr/lib/python3/dist-packages/odoo/addons/payment/controllers/portal.py", line 95, in payment_status_poll                                  
    tx_to_process._post_process_after_done()                                                                                                        
  File "/usr/lib/python3/dist-packages/odoo/addons/payment/models/payment_acquirer.py", line 780, in _post_process_after_done                       
    self._log_payment_transaction_received()                                                                                                        
  File "/usr/lib/python3/dist-packages/odoo/addons/sale/models/payment.py", line 53, in _log_payment_transaction_received                           
    super(PaymentTransaction, self)._log_payment_transaction_received()                                                                             
  File "/usr/lib/python3/dist-packages/odoo/addons/payment/models/payment_acquirer.py", line 700, in _log_payment_transaction_received              
    post_message = trans._get_payment_transaction_received_message()                                                                                
  File "/usr/lib/python3/dist-packages/odoo/addons/payment/models/payment_acquirer.py", line 680, in _get_payment_transaction_received_message      
    return message % tuple(message_vals)                                                                                                            
TypeError: not all arguments converted during string formatting
```

**Comment by Eric0329** [comment]
work around: https://github.com/MRLIVING/odoo/commit/4bac183a1ca7dca0325ef992276ebe1400f0a5a3
